# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablemateUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('active_table_id', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=64)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_addr', models.CharField(max_length=255)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('size', models.IntegerField(default=0)),
                ('server_id', models.CharField(max_length=64)),
                ('server_name', models.CharField(max_length=255)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_addr', models.CharField(max_length=255)),
                ('table_number', models.IntegerField(default=-1)),
                ('requested', models.BooleanField(default=False)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('time_start',),
            },
        ),
    ]
