# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
