# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='created',
            new_name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
